png(file='plot3.png')
plot(df$`Date/Time`, df$Sub_metering_1, type='l', xlab='', ylab='Energy sub metering')
lines(df$`Date/Time`, df$Sub_metering_2, type='l', col='red')
lines(df$`Date/Time`, df$Sub_metering_3, type='l', col='blue')
legend('topright', lty=1, col = c('black', 'red', 'blue'), legend=c('Sub_metering_1', 'Sub_metering_2', 'Sub_metering_3'))
dev.off()
